print("Hello Python")
print(2+2)
print("2+2")
print('Hello')
print('Olmaz')
print('Ali\'nin Dükkanı')
print("Ali'nin Dükkanı")
print('''Uzun uzun yolları aştım geldim''')
print('Uzun uzun yolları\naştım geldim')
